development:
  app_key: "pjcqjp6idcq8b8p"
  app_secret: "dcuhyqbgwdm4w0r"
  access_token: zz4zkprk67nsioph
  access_token_secret: b1y0706w1uv08z4
  user_id: 246278584
  access_type: "app_folder"

production:
  app_key: "ekyznzopqz5x2y0"
  app_secret: "7f67y0u4g42k92q"
  access_token: ds1ajwvwyxz78usu
  access_token_secret: j72ezg3k8gf12nc
  user_id: 10287287
  access_type: "app_folder"
