development:
  storage: :s3
  url: ":s3_domain_url"
  s3_host_name: "s3-ap-southeast-2.amazonaws.com"
  styles:
    high:  '600x600>'
    thumb: '100x100>'
  path:    ":style/:class/:id_image.:image_extension"
  s3_credentials:
    access_key_id:  "AKIAIPI3OX7XKWMK5KSQ"
    secret_access_key: "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"
    bucket: "bodyspace-development"
  s3_permissions: public_read
  s3_protocol: ''

production:
  storage: :s3
  url: ":s3_domain_url"
  s3_host_name: "s3-ap-southeast-2.amazonaws.com"
  styles:
    high:  '600x600>'
    thumb: '100x100>'
  path:    ":style/:class/:id_image.:image_extension"
  s3_credentials:
    access_key_id:  "AKIAIPI3OX7XKWMK5KSQ"
    secret_access_key: "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"
    bucket: "bodyspace-production"
  s3_permissions: public_read
  s3_protocol: ''